language: ruby
cache: bundler
rvm:
  - "1.9.3"
  - "2.1.5"
  - "2.2.0"
  - jruby-19mode # JRuby in 1.9 mode
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
