language: ruby
cache: bundler
rvm:
  - "1.9.3"
  - "2.1.9"
  - "2.2.4"
  - "2.3.1"
  - "jruby-9.0.5.0"
before_install:
  - gem install bundler
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
